### ISSUE TITLE
p-tsanev - VotingEscrowTruf.sol#migrateVestingLock() - migrating a lock does not reset delegate votes

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#14]
p-tsanev

high

# VotingEscrowTruf.sol#migrateVestingLock() - migrating a lock does not reset delegate votes

## Summary
The ``migrateVestingLock()`` function is used to transfer locks between users, but transferring the amounts and points, but it does not account the votes.

## Vulnerability Detail
When invoking ``migrateVestingLock()`` the old user's points get burned and the new user gets minted those points and receives a new lock. The old lock then gets deleted, but the function does not take into account the votes that the old user got delegated when he first created his lock.
As it can be seen in ``_stake``:
```solidity
        if (delegates(to) == address(0)) {
            // Delegate voting power to the receiver, if unregistered
            _delegate(to, to);
        }
```
Upon his first staking a user gets delegated voting power equal to the vote tokens he got minted. When migrating the lockup, a user's vote tokens get burned, but his delegated amount amount remains unchanged, because OZ's ``_delegate`` method saves a checkpoint of the vote amount. Unless a new delegate is invoked during migration, the old delegate would remain.
Another part of the issue is that the new user does not get delegated the voting power during migration, even though it might be the user's first lock, as per the logic of ``_stake`` above. Thus, a user who has no stake but receives a lock and an x amount of vote tokens could delegate himself even more tokens by then staking a y amount, thus the ``_delegate`` function would checkpoint x+y vote tokens.

## Impact
Improper voting power distribution and potential double-voting.

## Code Snippet
https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/VotingEscrowTruf.sol#L224-L252

## Tool used
https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/VotingEscrowTruf.sol#L154-L172

Manual Review

## Recommendation
Properly handle the delegations during migration to fully rid the old user of any voting prowess he had.

**Comment by ryuheimat** [comment]
https://github.com/truflation/truflation-contracts/pull/5

**Comment by securitygrid** [comment]
Escalate
`veTRUF.migrateVestingLock` is only called in `TrufVesting.migrateUser`. `MigrateUser` is called when the user loses his private key. This is not a common scenario. Therefore, it should be an M issue.

**Comment by sherlock-admin2** [comment]
> Escalate
> `veTRUF.migrateVestingLock` is only called in `TrufVesting.migrateUser`. `MigrateUser` is called when the user loses his private key. This is not a common scenario. Therefore, it should be an M issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by spacegliderrrr** [comment]
Not a real issue - if the user has had previous lock, new votes are automatically [delegated](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fd81a96f01cc42ef1c9a5399364968d0e07e9e90/contracts/token/ERC20/extensions/ERC20Votes.sol#L217C1-L221C6) and if the the user has not had a previous lock, they can always just call [delegate](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fd81a96f01cc42ef1c9a5399364968d0e07e9e90/contracts/token/ERC20/extensions/ERC20Votes.sol#L160C1-L162C6)

No real impact here, therefore should be low

**Comment by detectiveking123** [comment]
This is likely invalid for the reasons @spacegliderrrr mentioned

**Comment by PlamenTSV** [comment]
If a user is getting their lock migrated to a new address, that address definitely did not have a previous lock as migrations occur on account loss. If the user did not have an old account he won't just call delegate because of the assumption it is done internally, which is not the case. There is mismatch between different functionalities. That's the issue.
I agree it could be a medium depending on how the judge sees missing voting power in such an edge-case function.

**Comment by nevillehuang** [comment]
I agree with @spacegliderrrr this issue is invalid, given old delegated votes are already burned, with the new migrated user being able to invoke delegation to himself.

I believe the following reasoning by @PlamenTSV is moot given this is synonymous with the same reasoning by @Czar102  [here](https://github.com/sherlock-audit/2023-11-convergence-judging/issues/175#issuecomment-1880891071)

>  If the user did not have an old account he won't just call delegate because of the assumption it is done internally, which is not the case.

**Comment by PlamenTSV** [comment]
As far as I remember historical decisions do not hold weight, but: "I am also not sure if it is fair to assume any user would understand that delegation should be cleared first before such transfers unless explicitly made known to them/to watsons as a design decision during the contest"
All I see is inconsistent logic that would hurt an unknowing user that is not mentioned to be intended and is even fixed as of the time of writing.
We were not made aware of any logic that should invalidate this, like: "After migrating a lock, a user is supposed to manually delegate votes to himself" 
All I see is "Why should this be valid when a user can do it himself?". 
Also a user would not be able to vote in-between the times he delegates to himself or stakes more (which he cannot do as stated in another issue) so I could argue the user is robbed of privileges for an X amount of time as well. 

I agree it deserves a downgrade H->M.

**Comment by Czar102** [comment]
I think it is an informational issue. Planning to accept the escalation.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/14/#issuecomment-1895147682): accepted

**Comment by mstpr** [comment]
Fix LGTM

**Comment by ryuheimat** [comment]
Merged
