### ISSUE TITLE
J4X - Staking implementation does not account for staking duration

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#148]
J4X

medium

# Staking implementation does not account for staking duration

## Summary

The `Truflation` token's staking mechanism, as per its official documentation, promises higher Annual Percentage Yield (APY) for tokens locked for longer periods. However, the current smart contract implementation does not reflect this, as it distributes staking rewards linearly, regardless of the staking duration. This discrepancy between the documentation and the actual contract behavior leads to a misunderstanding about the rewards system.

## Vulnerability Detail

The [official documentation](https://whitepaper.truflation.com/tokenomics/truflation-token) of the Truflation token states:

```txt
Holders of the $TFI token can participate in the governance of the protocol by staking and locking their tokens for designated periods of time. The longer they lock their tokens, the higher the Annual Percentage Yield (APY) they earn.
```

The `VirtualStakingRewards` contract's actual implementation calculates `rewardPerToken` linearly, not accounting for the duration of staking:

```solidity
function rewardPerToken() public view returns (uint256) {
	if (_totalSupply == 0) {
		return rewardPerTokenStored;
	}
	return
		rewardPerTokenStored + (((lastTimeRewardApplicable() - lastUpdateTime) * rewardRate * 1e18) / _totalSupply);
}
```

Consequently, two users staking the same amount of tokens for different durations (e.g., one year vs. one day) end up receiving the same APY, contrary to the documented mechanism.
## Impact

This inconsistency leads to a loss of funds to users who stake their funds for a longer time expecting a higher APY than other shorter stakers, but actually receive the exact APY if the rewards are calculated based on amount/time.

## Code Snippet

https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/staking/VirtualStakingRewards.sol#L87-L93
## Tool used

Manual Review

## Recommendation

To align with the documented tokenomics and user expectations, the staking mechanism should be adjusted to factor in the duration of token staking. Implementing a system where the APY increases with longer staking periods would address this issue. This could involve modifying the `rewardPerToken` function or introducing additional logic to calculate rewards based on staking duration. Such changes would ensure that the actual contract behavior matches the documented mechanism, thereby maintaining the integrity and trust in the Truflation protocol.

Duplicate of #168

**Comment by ryuheimat** [comment]
If they staked longer, they get higher veTRUF token, thus they could have higher staking rewards.
