### ISSUE TITLE
astha0211 - Staking Reward amount calculation is wrong it is always same doesn't matter for how many days tokens have been staked

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#170]
astha0211

high

# Staking Reward amount calculation is wrong it is always same doesn't matter for how many days tokens have been staked

## Summary

Staking Reward amount will always be same for different lock durations like if I stake `100e18` for `1 days` and `4 days` reward amount will be `reward: 159999999999999667199 [1.599e20]` for all amount.

## Vulnerability Detail

Wrong reward amount calculation

considering Test code
In Setup()
```solidity 
        trufStakingRewards.setRewardsDuration(5 days);
        trufStakingRewards.notifyRewardAmount(200e18);
```

```solidity
      function testClaimedRewardsRemainsSameForDifferentInputs_Amount() external {
        uint256 amount = 100e18; ---Keep it same ---
        uint256 duration = 1 days; ----- change amount here -----
        _stake(amount, duration, alice, bob);
        vm.warp(block.timestamp + duration);
        vm.startPrank(bob);
        //vm.warp(block.timestamp + 1 days);
        veTRUF.claimReward();
        vm.stopPrank();
    }
```

Execute above code for below conditions :

`amount = 100e18`
`duration = 1 days`

Stake Event
`emit Stake(user: Bob: [0xDba2C8c2363677bA0514EF616592D81557e679B6], isVesting: false, lockupId: 1, amount: 100000000000000000000 [1e20], end: 1698631130 [1.698e9], points: 1826484018264840182 [1.826e18])`
RewardClaimed
`emit RewardPaid(user: Bob: [0xDba2C8c2363677bA0514EF616592D81557e679B6], reward: 159999999999999667199 [1.599e20])`

`amount = 100e18`
`duration = 4 days`

Stake Event
` emit Stake(user: Bob: [0xDba2C8c2363677bA0514EF616592D81557e679B6], isVesting: false, lockupId: 1, amount: 100000000000000000000 [1e20], end: 1698631130 [1.698e9], points: 1826484018264840182 [1.826e18])`
RewardClaimed
`emit RewardPaid(user: Bob: [0xDba2C8c2363677bA0514EF616592D81557e679B6], reward: 159999999999999667199 [1.599e20])`

Reason :
` (_balances[account] * (rewardPerToken() - userRewardPerTokenPaid[account]))` is giving same value for both amounts `39989028000000000000000000000000000000` divide by 1e18 `39989028000000000000` [3.999e19], where `userRewardPerTokenPaid[account]` is zero in both cases

## Impact

Reward is same for same amounts for different duration, if it is giving same reward for `1 days` and `4 days` why would user stake longer duration if user is getting same rewards for all durations.

## Code Snippet

```solidity
function earned(address account) public view returns (uint256) {
        return
            (_balances[account] *
                (rewardPerToken() - userRewardPerTokenPaid[account])) /
            1e18 +
            rewards[account];
    }
```

https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L95C1-L97C6

## Tool used

Manual Review

## Recommendation

` (_balances[account] * (rewardPerToken() - userRewardPerTokenPaid[account]))` is giving same value. `earned(address account)` needs to be updated so that such issues doe not occur

Duplicate of #168

**Comment by AsthaMishra** [comment]
This issue is not duplicate of  #168.
In this issue if user put same amount for different durations , reward will always be same. @ryuheimat

**Comment by sherlock-admin2** [comment]
> Escalate
> This issue is not duplicate of  #168.
> In this issue if user put same amount for different durations , reward will always be same. @ryuheimat 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
