### ISSUE TITLE
sandy - Malicious user can get twice the voting power.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-12-truflation-judging#205]
sandy

medium

# Malicious user can get twice the voting power.

## Summary
Malicious user can get twice the voting power.

## Vulnerability Detail
``migrateUser()``  of ``TrufVesting.sol`` is used to migrate the owner of vesting. It is used when user has lost his private key. This function then calls ``migrateVestingLock()`` of ``VotingEscrowTruf.sol`` which migrates user from one account to another account.

The problem lies in the ``_stake()`` of ``VotingEscrowTruf.sol`` which mints ``msg.sender`` points which increases the ``balanceOf(msg.sender).

Let's consider the following scenario:
1. Alice is a newly vested user with address A set by using ``setUserVesting()`` of ``TrufVesting.sol``.
2. Alice delegates his/her address to address B before staking to set delegatee of alice to address B.
3. After staking, Alice is minted points which increases the balance of Alice.
4. The Alice delegates again to transfer voting power.
5. Then Alice convinces the operation manager that she lost her private key and is migrated to address C.
6. After migration is completed, Alice is minted points [here](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/token/VotingEscrowTruf.sol#L246)
7. Alice again delegates her voting power to address B from new migrated address C.
8. Address B gets delegated the voting power twice. 

## Impact
Malicious user can get twice the voting power.

## Code Snippet
https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/token/TrufVesting.sol#L310

## Tool used
Manual Review

## Recommendation
Delegate voting power from old user to new user before migration.

**Comment by ryuheimat** [comment]
If we migrate Alice's account, Alice's veTRUF token balance will be removed, thus B's delegated voting power will be removed as well.
