### ISSUE TITLE
bigbick123456789000 - Inflexibility in Decreasing Max Allocation in Vesting Categories

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#24]
bigbick123456789000

medium

# Inflexibility in Decreasing Max Allocation in Vesting Categories

## Summary
The contract exhibits a lack of flexibility in allowing a decrease in the maximum allocation for vesting categories after their initial setup.
## Vulnerability Detail
The issue arises in the `setVestingCategory` function, which is responsible for adding or modifying vesting categories. The function performs various checks and token movements based on the provided parameters. However, when modifying an existing category (`id` is not `type(uint256).max`), the code ensures that the new `maxAllocation` is greater than or equal to the current value. If the new value is less than the current `maxAllocation`, the function reverts with a `MaxAllocationExceed()` error.
```solidity
if (id == type(uint256).max) {
    // ... (code for adding new category)
    tokenMove = int256(maxAllocation);
} else {
    if (categories[id].allocated > maxAllocation) {
        revert MaxAllocationExceed();
    }
    // ... (code for modifying existing category)
    tokenMove = int256(maxAllocation) - int256(categories[id].maxAllocation);
}
```
In the modification scenario, the function checks if the new maxAllocation is less than the current one. If the new value is smaller, the function reverts to prevent the decrease in `maxAllocation`.

## Impact
One potential impact of this lack of flexibility is that it hinders the ability to adapt vesting categories to changing requirements or conditions. Projects might need to decrease the maximum allocation for a category in response to evolving circumstances, and this restriction limits such adjustments.

## Code Snippet
[Link](https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/TrufVesting.sol#L484-L516)
## Tool used

Manual Review

## Recommendation
The contract's `setVestingCategory` function should be modified to allow a decrease in the maximum allocation. This may involve adjusting the token movements and associated checks to accommodate scenarios where the new `maxAllocation` is less than the existing one. 

Duplicate of #30

**Comment by ryuheimat** [comment]
This is not an issue.
