### ISSUE TITLE
cawfree - Insolvency Risk: `VirtualStakingRewards` may not possess enough `rewardTokens` to satisfy obligations.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#4]
cawfree

medium

# Insolvency Risk: `VirtualStakingRewards` may not possess enough `rewardTokens` to satisfy obligations.

## Summary

[`VirtualStakingRewards`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol) allows an established [`operator`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L22) to define the [`reward`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L144) for the next cycle via a call to [`notifyRewardAmount(uint256)`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L144), however it does not verify that the contract has sufficient balance to pay these rewards.

## Vulnerability Detail

When making a call to [`notifyRewardAmount(uint256)`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L144), care is taken to ensure that the contract's current reward token balance is capable of making users whole:

```solidity
// Ensure the provided reward amount is not more than the balance in the contract.
// This keeps the reward rate in the right range, preventing overflows due to
// very high values of rewardRate in the earned and rewardsPerToken functions;
// Reward + leftover must be less than 2^256 / 10^18 to avoid overflow.
uint256 balance = IERC20(rewardsToken).balanceOf(address(this));
if (rewardRate > balance / rewardsDuration) {
    revert InsufficientRewards();
}
```

However, this does not take into account current reward token obligations.

When extending a reward period, any unclaimed reward token balance in the contract will be mistakenly interpreted as reward token collateral that can be allocated for a new round of issuance.

Below, we show that an actor `ALICE` has `1 ether` staked for two `7 days` [`rewardDuration`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L27), each valued at `1 ether` in [`rewardsToken`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L24). Since `ALICE` doesn't redeem their tokens, [`VirtualStakingRewards`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol) assumes it possesses sufficient [`rewardsToken`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L24) capital for the second round:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.19;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";

import {VirtualStakingRewards} from "../../src/staking/VirtualStakingRewards.sol";
import {TruflationToken} from "../../src/token/TruflationToken.sol";

contract VirtualStakingRewardsSherlock is Test {

    // Warps the vm to a realistic timestamp.
    function _warp() internal {
        vm.roll(18936275);
        vm.warp(1704399287);
    }

    // Create a simple VirtualStakingRewards configuration with
    // a single `admin` who acts as the owner, operator and
    // distributor.
    function _initializeVirtualStaking() internal returns (
        VirtualStakingRewards virtualStakingRewards,
        TruflationToken truflationToken,
        address admin
    ) {
        admin = address(0x01);
        vm.startPrank(admin);
            truflationToken = new TruflationToken();
            virtualStakingRewards = new VirtualStakingRewards(admin, address(truflationToken));
            virtualStakingRewards.setOperator(admin);
        vm.stopPrank();
    }

    function test_sherlock_Insolvency() public {

        _warp() /* realistic_timestamp */;

        (VirtualStakingRewards staking, TruflationToken token, address operator) = _initializeVirtualStaking() /* deployment */;

        // Configure the reward for this period.
        vm.startPrank(operator);
            token.transfer(address(staking), 1 ether);
            staking.notifyRewardAmount(1 ether);
        vm.stopPrank();

        address ALICE = address(0x420);

        vm.prank(operator);
          staking.stake(ALICE, 1 ether);

        vm.warp(block.timestamp + 7 days);

        vm.prank(operator);
          staking.notifyRewardAmount(1 ether);

        vm.warp(block.timestamp + 7 days);

        assertEq(staking.earned(ALICE), 1999999999999814400);

        vm.prank(operator);
@>          vm.expectRevert("ERC20: transfer amount exceeds balance");
            staking.exit(ALICE);
    }

}
```

As demonstrated, attempts to withdraw `ALICE`'s reward `revert` with `"ERC20: transfer amount exceeds balance"`.

## Impact

- The staking contract can become insolvent in reward token balance, leaving some users unable to claim their rewards.
  - In order to sustain any liveliness of reward redemption in an insolvent contract, reward balances of honest users may need to be artificially reduced via a call to [`withdraw`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L117), else more reward tokens may need to be manually minted to fulfill existing obligations.
  - If [`VirtualStakingRewards`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol) is not owned by an EOA, is renounced, or is owned by a smart contract lacking required functionality, manually minting new tokens to satisfy demand may not be possible.
- Users who leave a reward cycle early in an insolvent configuration may receive amplified rewards compared to those who continue to stake.
- DoS when claiming rewards.

## Code Snippet

```solidity
function notifyRewardAmount(uint256 reward) external onlyRewardsDistribution updateReward(address(0)) {
    if (block.timestamp >= periodFinish) {
        rewardRate = reward / rewardsDuration;
    } else {
        uint256 remaining = periodFinish - block.timestamp;
        uint256 leftover = remaining * rewardRate;
        rewardRate = (reward + leftover) / rewardsDuration;
    }

    // Ensure the provided reward amount is not more than the balance in the contract.
    // This keeps the reward rate in the right range, preventing overflows due to
    // very high values of rewardRate in the earned and rewardsPerToken functions;
    // Reward + leftover must be less than 2^256 / 10^18 to avoid overflow.
    uint256 balance = IERC20(rewardsToken).balanceOf(address(this));
    if (rewardRate > balance / rewardsDuration) {
        revert InsufficientRewards();
    }

    lastUpdateTime = block.timestamp;
    periodFinish = block.timestamp + rewardsDuration;
    emit RewardAdded(reward);
}
```

## Tool used

Visual Studio Code, Foundry

## Recommendation

When calling [`notifyRewardAmount(uint256)`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L144), verify the amount of [`rewardsToken`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol#L24) in [`VirtualStakingRewards`](https://github.com/sherlock-audit/2023-12-truflation/blob/37ddbb69e0c7fb6510f1ec99162fd9172ec44733/truflation-contracts/src/staking/VirtualStakingRewards.sol) can fulfil both the new reward amount and the existing reward obligations.

**Comment by detectiveking123** [comment]
Escalate

This issue relies on an admin making making a mistake, which is invalid. The admin should always make sure there is sufficient balance.

**Comment by securitygrid** [comment]
Escalate
This report describles that operator doesn't send rewards to contract. This is operator's mistake. so it's invalid issue.

**Comment by nevillehuang** [comment]
@ryuheimat How is notifyRewardAmount called? Watsons are claiming it is an admin permissioned function but I'm unsure about the `onlyRewardsDistribution()` modifier, given you confirmed this issue, did you see some risk in this?

**Comment by securitygrid** [comment]
```
modifier onlyRewardsDistribution() {
        if (msg.sender != rewardsDistribution) {
            revert Forbidden(msg.sender);
        }
        _;
    }
```
`notifyRewardAmount` is only called by rewardsDistribution which is trusted. 

There is no token.transferFrom inside `notifyRewardAmount`. So rewardsDistribution needs to transfer reward to contract before calling `notifyRewardAmount`.

**Comment by sherlock-admin2** [comment]
> Escalate
> This report describles that operator doesn't send rewards to contract. This is operator's mistake. so it's invalid issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue relies on an admin making making a mistake, which is invalid. The admin should always make sure there is sufficient balance.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ryuheimat** [comment]
We will send rewards before call `notifyRewardAmount` function.
And `rewardDistribution` is trusted account.

**Comment by nevillehuang** [comment]
Got it in that case this issue should be invalid

**Comment by ddimitrov22** [comment]
However, the role was not described and marked as trusted on the audit contest page. The role is separate from the admin role, @nevillehuang in that case is it still invalid?

**Comment by ryuheimat** [comment]
`rewardsDistribution` is also trusted, so we won't fix this issue.

**Comment by Czar102** [comment]
Since it wasn't mentioned as a non-admin role, I'm willing to consider this a protocol admin as well and make the issue a low severity one. We will work on having the roles better communicated in the README.

**Comment by novaman33** [comment]
This is the same issue from another contest which was considered valid.
https://solodit.xyz/issues/m-09-stakingrewardssolnotifyrewardamount-improper-reward-balance-checks-can-make-some-users-unable-to-withdraw-their-rewards-code4rena-concur-finance-concur-finance-contest-git

**Comment by Czar102** [comment]
That is from a contest from C4 in early 2022. I'm not sure how is this relevant here.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [detectiveking123](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/4/#issuecomment-1894884507): accepted
- [securitygrid](https://github.com/sherlock-audit/2023-12-truflation-judging/issues/4/#issuecomment-1894960581): accepted
