### ISSUE TITLE
itsabinashb - VotingEscrowTurf::incorrect reward distribution

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#68]
itsabinashb

high

# VotingEscrowTurf::incorrect reward distribution

## Summary
In [`VotingEscrowTurf.sol`](https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/VotingEscrowTruf.sol) contract rewards is distributed in such a way that only first staker will get maximum reward and subsequent stakers will get 0 reward no matter how long they have been staking.

## Severity
High

## Relevant Github link:
https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/VotingEscrowTruf.sol#L257

## Vulnerability Detail
Here is the test:

```solidity
function test_rewardDistributionOccuringIncorrectly() external {
    console.log("trufStakingReward's balance: ", trufToken.balanceOf(address(trufStakingRewards)));
    vm.startPrank(alice);
    veTRUF.stake(1000, 10 days);
    vm.warp(block.timestamp + 10 days);
    console.log('reward before claiming: ', trufStakingRewards.earned(alice));
    console.log('before claiming the reward token balance of alice is : ', trufToken.balanceOf(alice));
    veTRUF.claimReward();
    console.log('after claiming the reward token balance of alice is : ', trufToken.balanceOf(alice));
    veTRUF.unstake(0);
    console.log("Alice unstaked her position");
    vm.stopPrank();
    console.log("trufStakingReward's balance after unstaking of Alice: ", trufToken.balanceOf(address(trufStakingRewards)));
    vm.startPrank(bob);
    trufToken.approve(address(veTRUF), type(uint256).max);
    console.log("Bob staked");
    veTRUF.stake(1000, 100 days);
    vm.warp(block.timestamp + 100 days);
    console.log("Bob's earned reward is: ", trufStakingRewards.earned(bob));
    veTRUF.unstake(0);
    console.log("Bob unstaked");
    console.log("trufStakingReward's balance after unstaking of Bob: ", trufToken.balanceOf(address(trufStakingRewards)));
    vm.startPrank(carol);
    trufToken.approve(address(veTRUF), type(uint256).max);
    console.log("Carol staked");
    veTRUF.stake(1000, 100 days);
    vm.warp(block.timestamp + 100 days);
    console.log("Carol's earned reward is: ", trufStakingRewards.earned(carol));
    veTRUF.unstake(0);
    console.log("Carol unstaked");
    console.log("trufStakingReward's balance after unstaking of Carol: ", trufToken.balanceOf(address(trufStakingRewards)));

  }
```

If we run this test we get:

```javascript
[PASS] test_rewardDistributionOccuringIncorrectly() (gas: 996043)
Logs:
  trufStakingReward's balance:  200000000000000000000
  reward before claiming:  199999999999999584000
  before claiming the reward token balance of alice is :  333333333333333333333332333
  after claiming the reward token balance of alice is :  333333533333333333332916333
  Alice unstaked her position
  trufStakingReward's balance after unstaking of Alice:  416000
  Bob staked
  Bob's earned reward is:  0
  Bob unstaked
  trufStakingReward's balance after unstaking of Bob:  416000
  Carol staked
  Carol's earned reward is:  0
  Carol unstaked
  trufStakingReward's balance after unstaking of Carol:  416000

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 2.28ms
```

So what is happening here?
One thing to note that reward is distributed by [`VirtualStakingRewards.sol`](https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/staking/VirtualStakingRewards.sol) i.e in this test `trufStakingRewards` contract. So first we can see the balance of `trufStakingReward` contract is : 200000000000000000000.  Then Alice staked 1000 Truf token for 10 days, after 10 days the claimable reward for Alice is: 199999999999999584000. You can see that surprisingly this amount is very high. If we substract this reward amount from the balance of `trufStakingRewards` contract then we will get only: 416000. So in `trufStakingRewards` contract ony 416000 Truf token is remaining to give reward, but the way reward is calculating and given away this amount is not sufficient, for that reason subsequent stakers like Bob, Carol are not getting any reward although they are staking for far longer time than Alice.
Even if Alice do not claim the reward and do not unstake still she will earn same amount of reward and Bob, Carol will not get any reward. See this in test:
```solidity
function test_rewardDistributionOccuringIncorrectly2() external {
    console.log("trufStakingReward's balance: ", trufToken.balanceOf(address(trufStakingRewards)));
    vm.prank(alice);

    veTRUF.stake(50e18, 10 days);
    console.log(' Alice staked');
    vm.warp(block.timestamp + 10 days);
    console.log("Alice's earned reward: ", trufStakingRewards.earned(alice));
    vm.startPrank(bob);
    trufToken.approve(address(veTRUF), type(uint256).max);

    veTRUF.stake(50e18, 100 days);
    console.log('Bob staked');
    vm.warp(block.timestamp + 100 days);
    console.log("Bob's earned reward is: ", trufStakingRewards.earned(bob));
    vm.stopPrank();
    vm.startPrank(carol);
    trufToken.approve(address(veTRUF), type(uint256).max);

    veTRUF.stake(1000, 100 days);
    console.log('Carol staked');
    vm.warp(block.timestamp + 100 days);
    console.log("Carol's earned reward is: ", trufStakingRewards.earned(carol));
  }
```
And result is:
```javascript
[PASS] test_rewardDistributionOccuringIncorrectly2() (gas: 987983)
Logs:
  trufStakingReward's balance:  200000000000000000000
   Alice staked
  Alice's earned reward:  199999999999999583999
  Bob staked
  Bob's earned reward is:  0
  Carol staked
  Carol's earned reward is:  0

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.74ms
```

## Impact
All stakers after first staker will not get any reward.
## Code Snippet
In `VirtualStakingRewards.sol`:

```solidity
modifier updateReward(address account) {
    rewardPerTokenStored = rewardPerToken(); 
    modifier updateReward(address account) {
    rewardPerTokenStored = rewardPerToken(); 
    lastUpdateTime = lastTimeRewardApplicable(); 
    if (account != address(0)) {
      rewards[account] = earned(account); 
      userRewardPerTokenPaid[account] = rewardPerTokenStored; 
    }
    _;
  }
```

```solidity
function stake(address user, uint256 amount) external updateReward(user) onlyOperator {
    if (amount == 0) {
      // @audit a user open a stake with minimum token, for ex- 0.00001. Will user get any profit by staking this low amount
      revert ZeroAmount(); // @audit what is the minimum / maximum staking time??
    }
    if (user == address(0)) {
      revert ZeroAddress();
    }
    _totalSupply += amount;
    _balances[user] += amount;
    emit Staked(user, amount);
  }
```

```solidity
function getReward(address user) public updateReward(user) returns (uint256 reward) {
    reward = rewards[user];
    if (reward != 0) {
      rewards[user] = 0;

      IERC20(rewardsToken).safeTransfer(user, reward); // @audit if staking is not actually happen how the reward will be given, where from the reward will come
      emit RewardPaid(user, reward);
    }
  }
```

```solidity
function withdraw(address user, uint256 amount) public updateReward(user) onlyOperator {
    // @audit is there any time limit after which a stake can be withdrawn??
    if (amount == 0) {
      revert ZeroAmount();
    }
    _totalSupply -= amount;
    _balances[user] -= amount; // @audit-issue the amount is not sent to the operator
    emit Withdrawn(user, amount);
  }
```

```solidity
function earned(address account) public view returns (uint256) {
    return (_balances[account] * (rewardPerToken() - userRewardPerTokenPaid[account])) / 1e18 + rewards[account]; // @audit rounding error?? & rewards[account] == 0
  }
```
## Tool used

Manual Review, Foundry

## Recommendation
The modifier `updateReward` in `VirtualStakingRewards.sol` contract is resposible for updating reward for an account through `rewards` mapping. All function mentioned in code snippet section is using this mofifier. So these codes are need to be checked.

Duplicate of #130

**Comment by itsabinashb** [comment]
Escalate
hello sir, sorry if i could not clarify the issue yet, give a chance, here is log of the test:
```
Logs:
  trufStakingReward's balance:  200000000000000000000
  reward before claiming:  199999999999999584000
  before claiming the reward token balance of alice is :  333333333333333333333332333
  after claiming the reward token balance of alice is :  333333533333333333332916333
  Alice unstaked her position
  trufStakingReward's balance after unstaking of Alice:  416000
  Bob staked
  Bob's earned reward is:  0
  Bob unstaked
  trufStakingReward's balance after unstaking of Bob:  416000
  Carol staked
  Carol's earned reward is:  0
  Carol unstaked
  trufStakingReward's balance after unstaking of Carol:  416000
  ```
The impact: **All stakers after first staker will not get any reward** means as we can see here Bob and Carol staked after alice i.e they are subsequent stakers of Alice, as Alice got the maximum amount of total amount of reward, which is actually the balance of `turfStakingReward` contract's balance, Bob and Carol could not get their reward. This may be because there are not enough balance to pay them. We can see the balance of `turfStakingReward` is 416000. The way reward is calculated that it is returning 0 for all subsequent staker of first  staker.

**Comment by sherlock-admin2** [comment]
> Escalate
> hello sir, sorry if i could not clarify the issue yet, give a chance, here is log of the test:
> ```
> Logs:
>   trufStakingReward's balance:  200000000000000000000
>   reward before claiming:  199999999999999584000
>   before claiming the reward token balance of alice is :  333333333333333333333332333
>   after claiming the reward token balance of alice is :  333333533333333333332916333
>   Alice unstaked her position
>   trufStakingReward's balance after unstaking of Alice:  416000
>   Bob staked
>   Bob's earned reward is:  0
>   Bob unstaked
>   trufStakingReward's balance after unstaking of Bob:  416000
>   Carol staked
>   Carol's earned reward is:  0
>   Carol unstaked
>   trufStakingReward's balance after unstaking of Carol:  416000
>   ```
> The impact: **All stakers after first staker will not get any reward** means as we can see here Bob and Carol staked after alice i.e they are subsequent stakers of Alice, as Alice got the maximum amount of total amount of reward, which is actually the balance of `turfStakingReward` contract's balance, Bob and Carol could not get their reward. This may be because there are not enough balance to pay them. We can see the balance of `turfStakingReward` is 416000. The way reward is calculated that it is returning 0 for all subsequent staker of first  staker.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by itsabinashb** [comment]
> @nevillehuang this submitter has not identified what the issue is, and makes the following false statement as to the impact: `All stakers after first staker will not get any reward.` this one is not a duplicate
hello sir, sorry if i could not clarify the issue yet, give a chance, here is log of the test:
```
Logs:
  trufStakingReward's balance:  200000000000000000000
  reward before claiming:  199999999999999584000
  before claiming the reward token balance of alice is :  333333333333333333333332333
  after claiming the reward token balance of alice is :  333333533333333333332916333
  Alice unstaked her position
  trufStakingReward's balance after unstaking of Alice:  416000
  Bob staked
  Bob's earned reward is:  0
  Bob unstaked
  trufStakingReward's balance after unstaking of Bob:  416000
  Carol staked
  Carol's earned reward is:  0
  Carol unstaked
  trufStakingReward's balance after unstaking of Carol:  416000
```
The impact: All stakers after first staker will not get any reward means as we can see here Bob and Carol staked after alice i.e they are subsequent stakers of Alice, as Alice got the maximum amount of total amount of reward, which is actually the balance of turfStakingReward contract's balance, Bob and Carol could not get their reward. This may be because there are not enough balance to pay them. We can see the balance of turfStakingReward is 416000. The way reward is calculated that it is returning 0 for all subsequent staker of first staker.

I could not open escalation so commented here. Please take a look. Thanks.
