### ISSUE TITLE
eeshenggoh - Maximum of vested period is not the same as in the whitepaper documentation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-truflation-judging#72]
eeshenggoh

high

# Maximum of vested period is not the same as in the whitepaper documentation

## Summary
The `MAX_DURATION` stated in the smart contract is the max amount of years vested in the smart contract. However, it is not following the whitepaper documentation.
## Vulnerability Detail
The whitepaper stated that the maximum number of years vested is 5 years but 3 years was implemented.
[Link](https://whitepaper.truflation.com/tokenomics/token-distribution)
## Impact
Stakers are not allowed to be vested for more than 3 years, hence losing rewards.
## Code Snippet
https://github.com/sherlock-audit/2023-12-truflation/blob/main/truflation-contracts/src/token/VotingEscrowTruf.sol#L48
## Tool used

Manual Review

## Recommendation
This adjustment places the multiplication before the division, which can help reduce the impact of rounding errors. 
```diff
    /// @dev Maximum duration
--  uint256 public constant MAX_DURATION = 365 days * 3; // 3 years
++  uint256 public constant MAX_DURATION = 365 days * 5; // change to 5 years
```

**Comment by goheesheng** [comment]
Isn't this going against, business logic, hence should be a medium? The intention was 5 years but 3 years was included instead.
